namespace: carcommerce-staging

backend:
  image:
    repository: carcommerceacr.azurecr.io/backend
    tag: ""  # overridden by --set
    pullPolicy: Always
  env:
    ASPNETCORE_ENVIRONMENT: Development
    ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=CarEcommerce;User=sa;Password=Password12345!;Encrypt=False;TrustServerCertificate=True;"
  containerPort: 80
  service:
    type: ClusterIP
    port: 8080

frontend:
  image:
    repository: carcommerceacr.azurecr.io/frontend
    tag: ""  # overridden by --set
    pullPolicy: Always
  env:
    ASPNETCORE_ENVIRONMENT: Development
  containerPort: 80
  service:
    type: ClusterIP
    port: 8080
