namespace: carcommerce

serviceAccount:
  create: false

service:
  port: 80
  type: ClusterIP

global:
  environment: production

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    acme.cert-manager.io/http01-ingress-class: "nginx"
  hosts:
    - host: production.4.207.233.155.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - production.4.207.233.155.nip.io
      secretName: carcommerce-prod-tls

hpa:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

backend:
  image:
    repository: carcommerceacr.azurecr.io/backend
    tag: ""  # Will be overridden by helm --set
    pullPolicy: Always
  containerPort: 80
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "500m"

frontend:
  image:
    repository: carcommerceacr.azurecr.io/frontend
    tag: ""  # Will be overridden by helm --set
    pullPolicy: Always
  env:
    ASPNETCORE_ENVIRONMENT: Production
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080
  resources:
    requests:
      cpu: "100m"
    limits:
      cpu: "500m"

sqlserver:
  image:
    repository: mcr.microsoft.com/mssql/server
    tag: 2022-latest
  saPassword: "Password12345!"
  port: 1433
  persistence:
    enabled: true
    storageClass: default
    accessMode: ReadWriteOnce
    size: 1Gi

azureKeyVault:
  name: carcommerce-kv
  tenantId: c0eaaf4a-860b-4699-a864-1075f4537dc1
