// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://img.classistatic.de/api/v1/mo-prod/images/42/42356da7-a4e3-4b3c-ba91-e029f7334251?rule=mo-1600.jpg",
                            Make = "Ford Fiesta",
                            Transmission = "Manual",
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://img.classistatic.de/api/v1/mo-prod/images/46/46681d0d-16d3-44a9-b14b-8de4607ae5de?rule=mo-1600.jpg",
                            Make = "Toyota Corolla",
                            Transmission = "Manual",
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://img.classistatic.de/api/v1/mo-prod/images/2a/2a0663b7-98f3-48f8-9d9d-5200aefbf0b4?rule=mo-1600.jpg",
                            Make = "BMW 3 Series",
                            Transmission = "Automatic",
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
