services:
  backend:
    build:
      context: ../Backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver
    networks:
      - productnetwork

  frontend:
    build:
      context: ../Frontend
    ports:
      - "5001:8080"
    depends_on:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BACKEND_URL=http://backend
    networks:
      - productnetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1434:1433"
    environment:
      MSSQL_SA_PASSWORD: "Password12345!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - productnetwork

networks:
  productnetwork:
  
volumes:
  sqlvolume:
