apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-{{ .Values.color }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
        color: {{ .Values.color }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.backend.env.ASPNETCORE_ENVIRONMENT | quote }}
            - name: ConnectionStrings__DefaultConnection
              value: {{ .Values.backend.env.ConnectionStrings__DefaultConnection | quote }}
