apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ .Release.Name }}-backend
  ports:
    - port: 80
      targetPort: {{ .Values.backend.service.port }}
