apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.backend.env.ASPNETCORE_ENVIRONMENT | quote }}

            {{- if eq .Values.namespace "carcommerce" }}
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sqlserver-db-password
                  key: sql-password
            - name: ConnectionStrings__DefaultConnection
              value: "Server=sqlserver;Database=CarEcommerce;User=sa;Password=$(SQL_PASSWORD);Encrypt=False;TrustServerCertificate=True;"
            {{- else }}
            - name: ConnectionStrings__DefaultConnection
              value: {{ .Values.backend.env.ConnectionStrings__DefaultConnection | quote }}
            {{- end }}

          {{- if .Values.azureKeyVault }}
          volumeMounts:
            - name: kv-secrets
              mountPath: /mnt/secrets
              readOnly: true
          {{- end }}

      {{- if .Values.azureKeyVault }}
      volumes:
        - name: kv-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-sql-secret-provider
            nodePublishSecretRef:
              name: aks-kv-secret
      {{- end }}
