apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sql-secret-provider
  namespace: carcommerce
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "carcommerce-kv"
    objects: |
      array:
        - objectName: sql-password
          objectType: secret
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
  secretObjects:
    - secretName: sqlserver-db-password
      type: Opaque
      data:
        - key: sql-password
          objectName: sql-password
