{{- if .Values.azureKeyVault }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-sql-secret-provider
  namespace: {{ .Values.namespace }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.azureKeyVault.name | quote }}
    objects: |
      array:
        - objectName: sql-password
          objectType: secret
    tenantId: {{ .Values.azureKeyVault.tenantId | quote }}
  secretObjects:
    - secretName: sqlserver-db-password
      type: Opaque
      data:
        - key: sql-password
          objectName: sql-password
{{- end }}